#!/bin/bash
#SBATCH -J class     # Job name
#SBATCH -o logs/class%j # Name of stdout output file(%j expands to jobId)
#SBATCH -e logs/class%j # Name of stderr output file(%j expands to jobId)
#SBATCH -p gtx          # Submit to the 'normal' or 'development' queue
#SBATCH -N 1                    # Total number of nodes requested (16 cores/node)
#SBATCH -n 1                    # Total number of mpi tasks requested
#SBATCH -t 24:00:00             # Max run time (hh:mm:ss) - 72 hours; this is determined by the queue you submit to, in this case gpu-long; please refer to the user guide for queue info.
#SBATCH --mail-user=rohan.nair@utexas.edu
#SBATCH --mail-type=ALL
# The next line is required if the user has more than one project
#SBATCH -A compdisc      # Allocation name to charge job against

module reset
module load python3
source venv/bin/activate

for i in {1..3}
do
    for j in 0 10 20 30 40 50 60 70 80 90 100
    do
        python3 code/train.py --model=cnn --bert-tokens=True --data-name=twitter_cnn_${j}_${i} --train=data/twitter/twitter_${j}_train.csv --valid=data/twitter/twitter_${j}_valid.csv --test=data/twitter/twitter_test.csv        
    done
done
